# Generated by Django 3.0.6 on 2020-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('thumbnail_key', models.CharField(max_length=50)),
                ('key_words', models.ManyToManyField(to='youtube_search.Tag')),
            ],
            options={
                'verbose_name_plural': 'YT Videos',
                'ordering': ['published_at'],
            },
        ),
    ]
