# Generated by Django 3.0.6 on 2020-05-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='video_id',
            new_name='video',
        ),
    ]
